In [45]:
import pandas as pd

In [46]:
df=pd.read_csv("spotify_millsongdata.csv")

In [47]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [48]:
df.shape

(57650, 4)

In [49]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [50]:
df=df.sample(5000).drop("link", axis=1).reset_index(drop=True)

In [51]:
df.head(10)

,artist,song,text
0,Kinks,A Little Bit Of Abuse,"One on the nose, one on the chin, \r\nYou bru..."
1,Don Henley,Through Your Hands,You were dreamin' \r\nOn a park bench \r\n'B...
2,The Beatles,If I Needed Someone,If I needed someone to love \r\nYou're the on...
3,Wham!,Battlestations,You ask too much of me \r\nYou try my patienc...
4,UB40,Cover Up,Cover up \r\nWith loving protection \r\nGuar...
5,Kylie Minogue,Silence,Lying on the ground together staring at the st...
6,Wang Chung,Eyes Of The Girl,"On her television, on her momma's radio \r\nS..."
7,Whitney Houston,I Believe In You And Me,I believe in you and me \r\nI believe that we...
8,Pogues,The Parting Glass,Of all the money that e'er I spent \r\nI've s...
9,Underworld,Little Speaker,Go \r\nDid you get these from round our's \r...

In [52]:
df['text'][0]

"One on the nose, one on the chin,  \r\nYou bruise so easy, so why stay with him?  \r\nHe uses you just like a human punching bag.  \r\nBut you don't complain, you're too scared to speak.  \r\nAnyway, it only really hurts you when you laugh,  \r\nAnd when you eat.  \r\nBut you can't break the pattern, week after week.  \r\nThe bruises show,  \r\nBut he must be special otherwise you'd just get up and go.  \r\nYou'll never let us know  \r\nExactly how you feel.  \r\nWhat's the use, the cynics say it's no excuse,  \r\nYou keep running back just to get a little bit of abuse.  \r\nYou say it's okay,  \r\nBut I say that it's not right.  \r\nYou wind him up, but you're living in fear,  \r\nYou keep going back but it ends in tears, oh.  \r\n  \r\nThat's quite a cut on the side of your head.  \r\nIs it from his fist, or did you really fall out of bed?  \r\nOh, so uncouth,  \r\nExcuse me, is this your tooth?  \r\nWhy do you stay, no one knows.  \r\nDo you really love him, or are you too scared to go?  \r\nYou're always nervous and on the edge of tears.  \r\nYou cry alone,  \r\nBut you never tell us what it's like when you get back home.  \r\nNo one will ever know  \r\nBecause you never show.  \r\nWhat's the use,  \r\nEveryone says you've got no excuse,  \r\nYou keep running back just to get a little bit of abuse.  \r\nYou say it's okay,  \r\nBut I say that it's not right.  \r\nOh, it's your secret, it's your life, who am I to criticize?  \r\nIt takes two sides to know it's true,  \r\nAnd maybe, he'll stay in love with you.  \r\nNo one will ever know,  \r\nBecause you never show.\r\n\r\n"

In [53]:
df.shape

(5000, 3)

In [54]:
df['text']=df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [55]:
df.tail(5)

,artist,song,text
4995,Culture Club,The Dream,like alice in wonderland \r the dream takes y...
4996,Leo Sayer,The End Of The Game,though he heard her clearly \r she said it so...
4997,Lou Reed,"I Love You, Suzanne",you broke my heart and you made me cry \r you...
4998,Tim Buckley,I Can't See You,"summer princess, midnight maiden \r when i fi..."
4999,Tom T. Hall,That's How I Got To Memphis,if you love somebody enough \r you'll follow ...

In [56]:
import nltk
from nltk.stem import PorterStemmer
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Artis\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Artis\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [57]:
stemmer=PorterStemmer()

In [58]:
def token(txt):
    tokens = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in tokens]
    return " ".join(a)

In [59]:
token("you are beautiful")

'you are beauti'

In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [61]:
df['text'].apply(lambda x: token(x))

0       one on the nose , one on the chin , you bruis ...
1       you were dreamin ' on a park bench 'bout a bro...
2       if i need someon to love you 're the one that ...
3       you ask too much of me you tri my patienc your...
4       cover up with love protect guard your love in ...
                              ...
4995    like alic in wonderland the dream take you by ...
4996    though he heard her clearli she said it so sin...
4997    you broke my heart and you made me cri you sai...
4998    summer princess , midnight maiden when i first...
4999    if you love somebodi enough you 'll follow whe...
Name: text, Length: 5000, dtype: object

In [62]:
tfid = TfidfVectorizer(analyzer='word', stop_words='english')

In [63]:
matrix=tfid.fit_transform(df['text'])

In [64]:
similar=cosine_similarity(matrix)

In [65]:
similar[0]

array([1.        , 0.02079762, 0.02220776, ..., 0.02894006, 0.02208922,
       0.04182301])

In [69]:
def recommender(song_name):
    idx=int(df[df['song'] == song_name].index[0])
    distance=sorted(list(enumerate(similar[idx])), reverse=True, key = lambda x:x[1])
    song = []
    for s_id in distance[1:20]:
        song.append(df.iloc[s_id[0]].song)
        return song

In [70]:
recommender("The End Of The Game")

['Come Fly With Me']